---
title: "Week 4 Lectures"
author: "Mathew Merryweather"
date: "28 August 2015"
output: html_document
---

## Editing Text Variables
Fixing character vectors
```{r}
if(!file.exists("./data")){dir.create("./data")}
if(!file.exists("./data/cameras.csv")){
    fileUrl = "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.csv?accessType=DOWNLOAD"
    download.file(fileUrl,destfile = "./data/cameras.csv",method = "curl")  
}
cameraData = read.csv("./data/cameras.csv")
names(cameraData)
## Format name cases
names(cameraData) = tolower(names(cameraData))
```

Fixing character vectors
```{r}
## often names are split by .
## . is a reserved char so have to escape it
splitNames = strsplit(names(cameraData),"\\.")
splitNames[[6]]
```

Fixing char vectors with `sapply`
```{r}
## remove periods and return only first part using strsplit from earliers
splitNames[[6]][1]
firstElement = function(x){x[1]}
sapply(splitNames,firstElement)
```

Peer review data
```{r}
fileUrl1 = "https://dl.dropboxusercontent.com/u/7710864/data/reviews-apr29.csv"
fileUrl2 = "https://dl.dropboxusercontent.com/u/7710864/data/solutions-apr29.csv"
download.file(fileUrl1,destfile = "./data/reviews.csv",method="curl")
download.file(fileUrl2,destfile = "./data/solutions.csv",method="curl")
reviews = read.csv("./data/reviews.csv")
solutions = read.csv("./data/solutions.csv")
head(reviews,2)
head(solutions,2)
```

fixing character vectors using `sub()`
```{r}
names(reviews)
## Sub only replace first instance
sub("_","",names(reviews))
```

Fixing character vectors using `gsub()`
```{r}
testName = "This_is_a_test"
sub("_","",testName)
## VS
gsub("_","",testName)
```

Finding values `grep()` and `grepl()`
```{r}
grep("Alameda",cameraData$intersection)
## grepl returns a Logical value as opposed to position
table(grepl("Alameda",cameraData$intersection))

cameraData2 = cameraData[!grepl("Alameda",cameraData$intersection),]

## Returns the matching values
grep("Alameda",cameraData$intersection,value=T)

## Checking for matches
length(grep("JeffStreet",cameraData$intersection))
## Length = 0 is a nice check
```

More useful string functions
 
```{r}
library(stringr)
nchar("Mat Merry")
substr("Mat Merry",1,3)
paste("Mat","Merry")
paste0("Mat","Merry")

str_trim(" Mat Merry ")
```
